### ISSUE TITLE
Can't compile TF serving on Ubuntu 16.10, with cuda 8.0, cudnn 5.1

### ISSUE THREAD

**Issue by vtablan** [tensorflow/serving#349]
I've been trying to compile TF serving, using the r0.5.1 tag, on Ubuntu 16.10, with python3. The build command fails with:

```
bazel build tensorflow_serving/...
WARNING: /home/vtablan/.cache/bazel/_bazel_vtablan/1a32f0c770daea3c91d81eb664e58997/external/org_tensorflow/tensorflow/workspace.bzl:63:5: tf_repo_name was specified to tf_workspace but is no longer used and will be removed in the future.
WARNING: /home/vtablan/.cache/bazel/_bazel_vtablan/1a32f0c770daea3c91d81eb664e58997/external/inception_model/WORKSPACE:1: Workspace name in /home/vtablan/.cache/bazel/_bazel_vtablan/1a32f0c770daea3c91d81eb664e58997/external/inception_model/WORKSPACE (@inception) does not match the name given in the repository's definition (@inception_model); this will cause a build error in future versions.
INFO: Found 256 targets...
ERROR: /home/vtablan/work/tf-serving/serving/tensorflow_serving/core/BUILD:186:1: Linking of rule '//tensorflow_serving/core:source_router_test' failed: gcc failed: error executing command /usr/bin/gcc -o bazel-out/local-fastbuild/bin/tensorflow_serving/core/source_router_test '-Wl,-rpath,$ORIGIN/../../_solib_k8/' -Lbazel-out/local-fastbuild/bin/_solib_k8 -pthread '-fuse-ld=gold' ... (remaining 9 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
bazel-out/local-fastbuild/bin/_solib_k8/libexternal_Sjemalloc_Slibjemalloc.so: error: undefined reference to 'pthread_key_create'
collect2: error: ld returned 1 exit status
INFO: Elapsed time: 25.578s, Critical Path: 22.18s
```

When I switch jemalloc off with:
```Do you wish to use jemalloc as the malloc implementation? (Linux only) [Y/n] n```

...it also fails with different but pthread-related errors, like so:

```
INFO: From Compiling external/org_tensorflow/tensorflow/core/protobuf/debug.pb_text.cc [for host]:
In file included from bazel-out/host/genfiles/external/org_tensorflow/tensorflow/core/protobuf/debug.pb_text-impl.h:5:0,
                 from bazel-out/host/genfiles/external/org_tensorflow/tensorflow/core/protobuf/debug.pb_text.cc:2:
external/org_tensorflow/tensorflow/core/lib/strings/proto_text_util.h: In instantiation of 'bool tensorflow::strings::ProtoParseNumericFromScanner(tensorflow::strings::Scanner*, T*) [with T = int]':
bazel-out/host/genfiles/external/org_tensorflow/tensorflow/core/protobuf/debug.pb_text.cc:93:96:   required from here
external/org_tensorflow/tensorflow/core/lib/strings/proto_text_util.h:167:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i = 0; i < numeric_str.size(); ++i) {
                     ^
ERROR: /home/vtablan/work/tf-serving/serving/tensorflow_serving/batching/BUILD:58:1: Linking of rule '//tensorflow_serving/batching:shared_batch_scheduler_test' failed: gcc failed: error executing command /usr/bin/gcc -o bazel-out/local-fastbuild/bin/tensorflow_serving/batching/shared_batch_scheduler_test '-Wl,-rpath,$ORIGIN/../../_solib_k8/' -Lbazel-out/local-fastbuild/bin/_solib_k8 -pthread ... (remaining 10 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
bazel-out/local-fastbuild/bin/_solib_k8/libexternal_Sgrpc_Slibgpr.so: error: undefined reference to 'pthread_once'
collect2: error: ld returned 1 exit status
INFO: Elapsed time: 488.811s, Critical Path: 232.22s
```

I also tried building just the tensorflow sourcetree, which succeeds.

My environment:
- CUDA: 8.0
- cuDNN: 5.1

```
/usr/bin/gcc --version
gcc (Ubuntu 5.4.1-2ubuntu2) 5.4.1 20160929
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

```
uname -a
Linux ieso-nlp 4.8.0-39-generic #42-Ubuntu SMP Mon Feb 20 11:47:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

```
git status
On branch r0.5.1
Your branch is up-to-date with 'origin/r0.5.1'.
```

Any idea what may be wrong?

Thanks!

**Comment by vtablan** [comment]
After further investigation it turns out that the compilation works with gcc-5 (5.4.1, to be precise). My Ubuntu defaults to gcc-6, which is linked from /usr/bin/gcc, and bazel insists on using that path by default.

Getting bazel to use another compiler is not trivial. I used the instructions listed [here](https://groups.google.com/forum/#!topic/bazel-discuss/U4yMaZGPqe4). Those are quite old, and for MacOS, so they need some adaptation. On my linux I found the cpp/tools directory to copy from in ~/.cache/bazel/_bazel\_\<username\>.

In case it's useful for anyone, here's the modified CROSSTOOL file that worked for me:
```
major_version: "local"
minor_version: ""
default_target_cpu: "same_as_host"

default_toolchain {
  cpu: "k8"
  toolchain_identifier: "local_linux"
}


default_toolchain {
  cpu: "local"
  toolchain_identifier: "local_linux"
}

toolchain {
  abi_version: "local"
  abi_libc_version: "local"
  builtin_sysroot: ""
  compiler: "compiler"
  host_system_name: "local"
  needsPic: true
  supports_gold_linker: false
  supports_incremental_linker: false
  supports_fission: false
  supports_interface_shared_objects: false
  supports_normalizing_ar: false
  supports_start_end_lib: false
  target_libc: "local"
  target_cpu: "k8"
  target_system_name: "local"
  toolchain_identifier: "local_linux"

  tool_path { name: "ar" path: "/usr/bin/ar" }
  tool_path { name: "compat-ld" path: "/usr/bin/ld" }
  tool_path { name: "cpp" path: "/usr/bin/cpp" }
  tool_path { name: "dwp" path: "/usr/bin/dwp" }
  tool_path { name: "gcc" path: "/usr/bin/gcc-5" }
  cxx_flag: "-std=c++0x"
  linker_flag: "-lstdc++"
  linker_flag: "-B/usr/bin/"

  # TODO(bazel-team): In theory, the path here ought to exactly match the path
  # used by gcc. That works because bazel currently doesn't track files at
  # absolute locations and has no remote execution, yet. However, this will need
  # to be fixed, maybe with auto-detection?
  cxx_builtin_include_directory: "/usr/lib/gcc/"
  cxx_builtin_include_directory: "/usr/local/include"
  cxx_builtin_include_directory: "/usr/include"
  tool_path { name: "gcov" path: "/usr/bin/gcov" }

  # C(++) compiles invoke the compiler (as that is the one knowing where
  # to find libraries), but we provide LD so other rules can invoke the linker.
  tool_path { name: "ld" path: "/usr/bin/ld" }

  tool_path { name: "nm" path: "/usr/bin/nm" }
  tool_path { name: "objcopy" path: "/usr/bin/objcopy" }
  objcopy_embed_flag: "-I"
  objcopy_embed_flag: "binary"
  tool_path { name: "objdump" path: "/usr/bin/objdump" }
  tool_path { name: "strip" path: "/usr/bin/strip" }

  # Anticipated future default.
  unfiltered_cxx_flag: "-no-canonical-prefixes"
  unfiltered_cxx_flag: "-fno-canonical-system-headers"

  # Make C++ compilation deterministic. Use linkstamping instead of these
  # compiler symbols.
  unfiltered_cxx_flag: "-Wno-builtin-macro-redefined"
  unfiltered_cxx_flag: "-D__DATE__=\"redacted\""
  unfiltered_cxx_flag: "-D__TIMESTAMP__=\"redacted\""
  unfiltered_cxx_flag: "-D__TIME__=\"redacted\""

  # Security hardening on by default.
  # Conservative choice; -D_FORTIFY_SOURCE=2 may be unsafe in some cases.
  # We need to undef it before redefining it as some distributions now have
  # it enabled by default.
  compiler_flag: "-U_FORTIFY_SOURCE"
  compiler_flag: "-D_FORTIFY_SOURCE=1"
  compiler_flag: "-fstack-protector"
  linker_flag: "-Wl,-z,relro,-z,now"

  # Enable coloring even if there's no attached terminal. Bazel removes the
  # escape sequences if --nocolor is specified. This isn't supported by gcc
  # on Ubuntu 14.04.
  # compiler_flag: "-fcolor-diagnostics"

  # All warnings are enabled. Maybe enable -Werror as well?
  compiler_flag: "-Wall"
  # Enable a few more warnings that aren't part of -Wall.
  compiler_flag: "-Wunused-but-set-parameter"
  # But disable some that are problematic.
  compiler_flag: "-Wno-free-nonheap-object" # has false positives

  # Keep stack frames for debugging, even in opt mode.
  compiler_flag: "-fno-omit-frame-pointer"

  # Anticipated future default.
  linker_flag: "-no-canonical-prefixes"
  # Have gcc return the exit code from ld.
  linker_flag: "-pass-exit-codes"
  # Stamp the binary with a unique identifier.
  linker_flag: "-Wl,--build-id=md5"
  linker_flag: "-Wl,--hash-style=gnu"
  # Gold linker only? Can we enable this by default?
  # linker_flag: "-Wl,--warn-execstack"
  # linker_flag: "-Wl,--detect-odr-violations"

  compilation_mode_flags {
    mode: DBG
    # Enable debug symbols.
    compiler_flag: "-g"
  }
  compilation_mode_flags {
    mode: OPT

    # No debug symbols.
    # Maybe we should enable https://gcc.gnu.org/wiki/DebugFission for opt or
    # even generally? However, that can't happen here, as it requires special
    # handling in Bazel.
    compiler_flag: "-g0"

    # Conservative choice for -O
    # -O3 can increase binary size and even slow down the resulting binaries.
    # Profile first and / or use FDO if you need better performance than this.
    compiler_flag: "-O2"

    # Disable assertions
    compiler_flag: "-DNDEBUG"

    # Removal of unused code and data at link time (can this increase binary size in some cases?).
    compiler_flag: "-ffunction-sections"
    compiler_flag: "-fdata-sections"
    linker_flag: "-Wl,--gc-sections"
  }
  linking_mode_flags { mode: DYNAMIC }
}
```
Note that your CPU may be different from mine, so change the value accordingly.

The successful build was launched with this command: 
```bazel build --crosstool_top=//tools/cpp:toolchain  --verbose_failures tensorflow_serving/...```

So, 'it works'... 

Not closing this issue because the hard dependency on gcc-5 should be documented in the installation instructions, and the build process should fail with some helpful message when building is attempted with a non-supported compiler version.

**Comment by vtablan** [comment]
I was able to compile the 0.5.1 tagged version of the source code using the script produced by @jorgemf at https://github.com/tensorflow/serving/issues/318. Closing this issue.
