### ISSUE TITLE
TF Serving doesn't build with gcc 4.8.5

### ISSUE THREAD

**Issue by goswamig** [tensorflow/serving#1001]
gcc version: 4.8.5

**Comment by netfs** [comment]
can you upgrade to gcc 4.9. see https://github.com/nlohmann/json/issues/109 for more details.

**Comment by gautamkmr** [comment]
Is there anyway to bypass the unit test compilation ? We are using conda environment by default couldnt find a gcc version bigger than 4.8.5

**Comment by netfs** [comment]
if you control the compilation, you could certainly change the sources to skip the tests. i'd advise against that, as you would loose test coverage. short of that i am unsure what else could be done.

patches/contributions to make the current code work (also) on gcc 4.8.5 are welcome.

**Comment by gautamvasudevan** [comment]
Here's the error:
TF -serving (1.8 and 1.9) build from source failed with tensorflow_serving/util/json_tensor_test.cc:60:43: error: unterminated raw string

Retitiling for clarity.

**Comment by sathyamoorthyrr** [comment]
> if you control the compilation, you could certainly change the sources to skip the tests. i'd advise against that, as you would loose test coverage. short of that i am unsure what else could be done.
> 
> patches/contributions to make the current code work (also) on gcc 4.8.5 are welcome.

By the way, how could I skip tests?

**Comment by pindinagesh** [comment]
Hi @goswamig 

Could you kindly check gcc with latest version of TF Serving and please have a look at this [issue](https://github.com/tensorflow/serving/issues/349) which is addressed already. Thanks!

**Comment by pindinagesh** [comment]
@goswamig 

Closing this issue due to inactivity. Please feel free to reopen if this still exists. Thanks
