### ISSUE TITLE
building MKL container fails on r2.1 branch.

### ISSUE THREAD

**Issue by ashahba** [tensorflow/serving#1603]
While running
```
docker build --build-arg TF_SERVING_VERSION_GIT_BRANCH=r2.0 -f Dockerfile.devel-mkl . -t serving-devel-mkl:r2.0
```
I'm getting the following error:
```
Step 20/27 : RUN bazel build --color=yes --curses=yes     ${TF_SERVING_BAZEL_OPTIONS}     --verbose_failures     --output_filter=DONT_MATCH_ANYTHING     ${TF_SERVING_BUILD_OPTIONS}     tensorflow_serving/model_servers:tensorflow_model_server &&     cp bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server     /usr/local/bin/
 ---> Running in 55ba108f9dab
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Analysed target //tensorflow_serving/model_servers:tensorflow_model_server (164 packages loaded, 11711 targets configured).
INFO: Found 1 target...
ERROR: /root/.cache/bazel/_bazel_root/e53bbb0b0da4e26d24b415310219b953/external/org_tensorflow/tensorflow/lite/experimental/ruy/BUILD:271:1: C++ compilation of rule '@org_tensorflow//tensorflow/lite/experimental/ruy:kernel' failed (Exit 1): gcc failed: error executing command 
  (cd /root/.cache/bazel/_bazel_root/e53bbb0b0da4e26d24b415310219b953/execroot/tf_serving && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/usr/bin/python \
  /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -MD -MF bazel-out/k8-opt/bin/external/org_tensorflow/tensorflow/lite/experimental/ruy/_objs/kernel/kernel_avx512.d '-frandom-seed=bazel-out/k8-opt/bin/external/org_tensorflow/tensorflow/lite/experimental/ruy/_objs/kernel/kernel_avx512.o' -iquote external/org_tensorflow -iquote bazel-out/k8-opt/genfiles/external/org_tensorflow -iquote bazel-out/k8-opt/bin/external/org_tensorflow -iquote external/gemmlowp -iquote bazel-out/k8-opt/genfiles/external/gemmlowp -iquote bazel-out/k8-opt/bin/external/gemmlowp '-march=native' -O3 '-std=c++14' '-D_GLIBCXX_USE_CXX11_ABI=0' -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/org_tensorflow/tensorflow/lite/experimental/ruy/kernel_avx512.cc -o bazel-out/k8-opt/bin/external/org_tensorflow/tensorflow/lite/experimental/ruy/_objs/kernel/kernel_avx512.o)
Execution platform: @bazel_tools//platforms:host_platform
In file included from external/org_tensorflow/tensorflow/lite/experimental/ruy/kernel_avx512.cc:18:0:
external/org_tensorflow/tensorflow/lite/experimental/ruy/kernel.h:613:9: warning: multi-line comment [-Wcomment]
 #endif  // (RUY_PLATFORM(NEON_64) || RUY_PLATFORM(NEON_32) || \
         ^
In file included from external/gemmlowp/fixedpoint/fixedpoint.h:895:0,
                 from external/org_tensorflow/tensorflow/lite/experimental/ruy/kernel.h:22,
                 from external/org_tensorflow/tensorflow/lite/experimental/ruy/kernel_avx512.cc:18:
external/gemmlowp/fixedpoint/./fixedpoint_sse.h:43:39: warning: ignoring attributes on template argument '__m128i {aka __vector(2) long long int}' [-Wignored-attributes]
 struct FixedPointRawTypeTraits<__m128i> {
                                       ^
In file included from external/org_tensorflow/tensorflow/lite/experimental/ruy/kernel_avx512.cc:18:0:
external/org_tensorflow/tensorflow/lite/experimental/ruy/kernel.h: In function 'void ruy::MakeKernelParamsFloat(const ruy::PackedMatrix<float>&, const ruy::PackedMatrix<float>&, const ruy::BasicSpec<float, float>&, int, int, int, int, ruy::Matrix<float>*, ruy::KernelParamsFloat<LhsCols, RhsCols>*)':
external/org_tensorflow/tensorflow/lite/experimental/ruy/kernel.h:456:53: warning: typedef 'using Params = struct ruy::KernelParamsFloat<LhsCols, RhsCols>' locally defined but not used [-Wunused-local-typedefs]
   using Params = KernelParamsFloat<LhsCols, RhsCols>;
                                                     ^
external/org_tensorflow/tensorflow/lite/experimental/ruy/kernel_avx512.cc: In function 'void ruy::Kernel8bitAvx512(const ruy::KernelParams8bit<16, 16>&)':
external/org_tensorflow/tensorflow/lite/experimental/ruy/kernel_avx512.cc:111:34: error: '_mm512_loadu_epi8' was not declared in this scope
         const __m512i lhs_data = _mm512_loadu_epi8(lhs_ptr);
                                  ^~~~~~~~~~~~~~~~~
external/org_tensorflow/tensorflow/lite/experimental/ruy/kernel_avx512.cc:111:34: note: suggested alternative: '_mm512_add_epi8'
         const __m512i lhs_data = _mm512_loadu_epi8(lhs_ptr);
                                  ^~~~~~~~~~~~~~~~~
                                  _mm512_add_epi8
external/org_tensorflow/tensorflow/lite/experimental/ruy/kernel_avx512.cc:161:32: error: '_mm512_loadu_epi32' was not declared in this scope
                                _mm512_loadu_epi32(&params.lhs_sums[row]));
                                ^~~~~~~~~~~~~~~~~~
external/org_tensorflow/tensorflow/lite/experimental/ruy/kernel_avx512.cc:161:32: note: suggested alternative: '_mm512_load_epi32'
                                _mm512_loadu_epi32(&params.lhs_sums[row]));
                                ^~~~~~~~~~~~~~~~~~
                                _mm512_load_epi32
external/org_tensorflow/tensorflow/lite/experimental/ruy/kernel_avx512.cc:170:32: error: '_mm512_loadu_epi32' was not declared in this scope
                                _mm512_loadu_epi32(&params.rhs_sums[col]));
                                ^~~~~~~~~~~~~~~~~~
external/org_tensorflow/tensorflow/lite/experimental/ruy/kernel_avx512.cc:170:32: note: suggested alternative: '_mm512_load_epi32'
                                _mm512_loadu_epi32(&params.rhs_sums[col]));
                                ^~~~~~~~~~~~~~~~~~
                                _mm512_load_epi32
external/org_tensorflow/tensorflow/lite/experimental/ruy/kernel_avx512.cc:277:13: error: '_mm_storeu_epi8' was not declared in this scope
             _mm_storeu_epi8(tmp_ptr, _mm512_cvtepi32_epi8(accum_data_v[j]));
             ^~~~~~~~~~~~~~~
external/org_tensorflow/tensorflow/lite/experimental/ruy/kernel_avx512.cc:277:13: note: suggested alternative: '_mm_store_epi64'
             _mm_storeu_epi8(tmp_ptr, _mm512_cvtepi32_epi8(accum_data_v[j]));
             ^~~~~~~~~~~~~~~
             _mm_store_epi64
external/org_tensorflow/tensorflow/lite/experimental/ruy/kernel_avx512.cc:293:13: error: '_mm_storeu_epi8' was not declared in this scope
             _mm_storeu_epi8(tmp_ptr, _mm512_cvtepi32_epi8(accum_data_v[j]));
             ^~~~~~~~~~~~~~~
external/org_tensorflow/tensorflow/lite/experimental/ruy/kernel_avx512.cc:293:13: note: suggested alternative: '_mm_store_epi64'
             _mm_storeu_epi8(tmp_ptr, _mm512_cvtepi32_epi8(accum_data_v[j]));
             ^~~~~~~~~~~~~~~
             _mm_store_epi64
external/org_tensorflow/tensorflow/lite/experimental/ruy/kernel_avx512.cc:309:13: error: '_mm256_storeu_epi16' was not declared in this scope
             _mm256_storeu_epi16(tmp_ptr,
             ^~~~~~~~~~~~~~~~~~~
external/org_tensorflow/tensorflow/lite/experimental/ruy/kernel_avx512.cc:309:13: note: suggested alternative: '_mm256_store_epi64'
             _mm256_storeu_epi16(tmp_ptr,
             ^~~~~~~~~~~~~~~~~~~
             _mm256_store_epi64
external/org_tensorflow/tensorflow/lite/experimental/ruy/kernel_avx512.cc:326:13: error: '_mm512_storeu_epi32' was not declared in this scope
             _mm512_storeu_epi32(tmp_ptr, accum_data_v[j]);
             ^~~~~~~~~~~~~~~~~~~
external/org_tensorflow/tensorflow/lite/experimental/ruy/kernel_avx512.cc:326:13: note: suggested alternative: '_mm512_store_epi32'
             _mm512_storeu_epi32(tmp_ptr, accum_data_v[j]);
             ^~~~~~~~~~~~~~~~~~~
             _mm512_store_epi32
Target //tensorflow_serving/model_servers:tensorflow_model_server failed to build
INFO: Elapsed time: 182.991s, Critical Path: 130.23s
INFO: 3791 processes: 3791 local.
FAILED: Build did NOT complete successfully
The command '/bin/sh -c bazel build --color=yes --curses=yes     ${TF_SERVING_BAZEL_OPTIONS}     --verbose_failures     --output_filter=DONT_MATCH_ANYTHING     ${TF_SERVING_BUILD_OPTIONS}     tensorflow_serving/model_servers:tensorflow_model_server &&     cp bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server     /usr/local/bin/' returned a non-zero code: 1```

**Comment by vdevaram** [comment]
Even issue is there on master - 
ERROR: /root/.cache/bazel/_bazel_root/e53bbb0b0da4e26d24b415310219b953/external/upb/BUILD:57:1: C++ compilation of rule '@upb//:upb' failed (Exit 1)
external/upb/upb/table.c: In function 'upb_inttable_pop':
external/upb/upb/table.c:588:10: error: 'val.val' may be used uninitialized in this function [-Werror=maybe-uninitialized]
   return val;
          ^~~
cc1: all warnings being treated as errors
Target //tensorflow_serving/model_servers:tensorflow_model_server failed to build
INFO: Elapsed time: 79.057s, Critical Path: 16.17s
INFO: 1570 processes: 1570 local.
FAILED: Build did NOT complete successfully
The command '/bin/sh -c bazel build --color=yes --curses=yes     ${TF_SERVING_BAZEL_OPTIONS}     --verbose_failures     --output_filter=DONT_MATCH_ANYTHING     ${TF_SERVING_BUILD_OPTIONS}     tensorflow_serving/model_servers:tensorflow_model_server &&     cp bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server     /usr/local/bin/' returned a non-zero code: 1

**Comment by ashahba** [comment]
@vdevaram As far as I know `master` fails both with and without `mkl`.
We'll take take another look and provide update here.

**Comment by ashahba** [comment]
@vdevaram would you please be able to try this one? #1601

**Comment by lilao** [comment]
@vdevaram Please see https://github.com/tensorflow/serving/issues/1596 for the 'val.val' issue. Please let us know if this does not address your question.

**Comment by lilao** [comment]
@ashahba https://github.com/tensorflow/tensorflow/issues/31187 reported a similar issue as yours. Can you take a look to see if it resolves your problem?

**Comment by lilao** [comment]
@ashahba Can you please verify if you can build with 2.2.0-rc2? We are ready to release 2.2.0. Please let us know at your earliest convenience if you encounter any problems. Thanks!

**Comment by gowthamkpr** [comment]
@ashahba Can you please respond to the above comment so that we can take the discussion forward. Thanks!

**Comment by ashahba** [comment]
Oh, sorry just saw this. Let me try.

**Comment by ashahba** [comment]
No, both `2.2.0-rc2` and `2.2.0` fails for me with:
```
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/387c3f74fd8efdc0be464b0e1a8033cc1eeb739c.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
INFO: Analyzed target //tensorflow_serving/model_servers:tensorflow_model_server (223 packages loaded, 16583 targets configured).
INFO: Found 1 target...
ERROR: /root/.cache/bazel/_bazel_root/e53bbb0b0da4e26d24b415310219b953/external/upb/BUILD:57:1: C++ compilation of rule '@upb//:upb' failed (Exit 1)
external/upb/upb/table.c: In function 'upb_inttable_pop':
external/upb/upb/table.c:588:10: error: 'val.val' may be used uninitialized in this function [-Werror=maybe-uninitialized]
   return val;
          ^~~
cc1: all warnings being treated as errors
Target //tensorflow_serving/model_servers:tensorflow_model_server failed to build
INFO: Elapsed time: 175.983s, Critical Path: 102.56s
INFO: 2973 processes: 2973 local.
FAILED: Build did NOT complete successfully
```

**Comment by ashahba** [comment]
However if I use `TF_SERVING_BUILD_OPTIONS="--config=release"` it builds fine.

**Comment by ashahba** [comment]
@MahdiEsf I'll try this again tomorrow and I'll post here.

**Comment by MahdiEsf** [comment]
@ashahba Thanks. We were able to build images successfully with updated files.

**Comment by rmothukuru** [comment]
@ashahba,
Can you please confirm if your issue is resolved so that we can close this issue? Thanks!
